version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: copy env file
          command: cp .env.example .env
      - run: npm install
      - run: npm test
  copy-to-preview:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Set Conf
          command: git config --global push.default matching
      - run: 
          name: Set Gitmail
          command: git config --global user.email "robloxfilmcam@gmail.com"
      - run:
          name: Set Gituser
          command: git config --global user.name "LordDamionDevil"
      - run:
          name: Create Files
          command: wget -O .env https://crunchyblock.com/nodeplanet/.env && wget -O now.json https://crunchyblock.com/nodeplanet/now.json && wget -O now.env https://crunchyblock.com/nodeplanet/now.env
      - run:
          name: Commit
          command: git add . && git commit -am "Add Vercel Hosting"
      - run:
          name: Push
          command: git push --force origin master:preview

workflows:
    build-and-test:
      jobs:
        - build-and-test:
            filters:
              branches:
                only:
                  - master
        - copy-to-preview:
            filters:
              branches:
                only:
                  - master
            requires:
              - build-and-test
